name: Test Applications
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  Test-Applications:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting Tests for Applications"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      - run: npm install
      - run: npm test
